[versions]
springboot = "3.3.4"

[libraries]
spring-boot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springboot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springboot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springboot" }
log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2", version.ref = "springboot" }
mongo = { module = "org.springframework.boot:spring-boot-starter-data-mongodb", version.ref = "springboot" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }
